export const SRSPolicy = {
  MIN_DIFFICULTY: 0,
  MAX_DIFFICULTY: 100,
  MAX_INTERVAL_DAYS: 36500, // 100 years
  LEARNING_STEPS_DAYS: [0, 1, 3, 7] as readonly number[],
  MATURE_THRESHOLD_SUCCESSES: 4,
  
  // Adjustments
  DIFFICULTY_ADJUSTMENT_CORRECT: -5,
  DIFFICULTY_ADJUSTMENT_INCORRECT: 15,
  RECALL_PENALTY_INCORRECT: 20,
  RECALL_BONUS_CORRECT: 10,
  
  // Bounds & Constants
  MATURE_INITIAL_INTERVAL_DAYS: 14,
  BASE_MATURE_MULTIPLIER: 1.5,
  DIFFICULTY_DECAY_FACTOR: 100,
  RECALL_CAP: 100,
  MIN_RECALL: 0,
} as const;
